name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-ver: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js v${{ matrix.node-ver }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-ver }}
        cache: 'npm'
    - name: Clean install the project
      run: npm ci
    - name: Build the project
      run: npm run build --if-present
    - name: Test the project
      run: npm test
